import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
import os

class QuickDrawBrain(nn.Module):
    def __init__(self):
        super(QuickDrawBrain, self).__init__()
        # Layer 1: Convolution (Magnifying glass)
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, padding=1)
        # Layer 2: Pooling (Shrinking)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        # Layer 3 is flattening, handled in forward()
        # Layer 4: Dense Output (Decision maker for 10 categories)
        self.dense = nn.Linear(in_features=16 * 14 * 14, out_features=35)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = torch.flatten(x, 1) 
        x = self.dense(x)
        return x

print("Loading NPY_FILE from the 'NPY_FILE/' folder...")

# Load the numpy arrays generated by your first script
X_train = np.load('NPY_FILE/X_train.npy')
y_train = np.load('NPY_FILE/y_train.npy')
X_val = np.load('NPY_FILE/X_val.npy')
y_val = np.load('NPY_FILE/y_val.npy')

print("Converting to PyTorch Tensors and normalizing...")

# Convert, reshape for Layer 1 injection, and normalize pixel values (0 to 1)
X_train_tensor = torch.tensor(X_train, dtype=torch.float32).view(-1, 1, 28, 28) / 255.0
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_val_tensor = torch.tensor(X_val, dtype=torch.float32).view(-1, 1, 28, 28) / 255.0
y_val_tensor = torch.tensor(y_val, dtype=torch.long)

# Batch the training data to prevent memory crashes
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

model = QuickDrawBrain()
criterion = nn.CrossEntropyLoss()           # The Teacher (Loss Function)
optimizer = optim.Adam(model.parameters(), lr=0.001) # The Updater
epochs = 20

print(f"\nStarting training for {epochs} epochs...")

for epoch in range(epochs):
    model.train() # Set to training mode
    running_loss = 0.0
    
    for images, labels in train_loader:
        optimizer.zero_grad()           # Clear old memory
        outputs = model(images)         # AI makes a guess
        loss = criterion(outputs, labels) # Teacher grades it
        loss.backward()                 # Calculate mistakes
        optimizer.step()                # Adjust the brain connections
        
        running_loss += loss.item()
        
    avg_loss = running_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{epochs}] complete. Average Loss: {avg_loss:.4f}")

print("\nTraining finished! Testing on hidden validation set...")

model.eval() # Set to evaluation mode (turns off adjusting connections)
correct_guesses = 0
total_drawings = len(y_val_tensor)

with torch.no_grad():
    test_outputs = model(X_val_tensor)
    _, predictions = torch.max(test_outputs, 1)
    correct_guesses = (predictions == y_val_tensor).sum().item()

accuracy = (correct_guesses / total_drawings) * 100
print(f"Final Validation Accuracy: {accuracy:.2f}%")

# Once we are happy with the accuracy, we save the trained weights
save_path = 'trained_brain.pth'
torch.save(model.state_dict(), save_path)

print(f"\nSuccess! The trained AI has been saved as '{save_path}'.")
print("It is now ready to be plugged into your game server!")